### 1. 异常处理中的构造与析构

```c++
#include<iostream>
#include<string>
using namespace std;

class MyException{
	public:
		MyException(const string &message):message(message){}
		~MyException(){}
		const string &getMessage()const{return message;}
	private:
		string message;
};

class Demo{
	public:
		Demo(){
			cout<<"Constructor of Demo"<<endl;
		}
		~Demo(){
			cout<<"Destructor of Demo"<<endl; 
		}
};

void func() throw(MyException){
	Demo d;
	cout<<"Throw MyException in func()"<<endl;
	throw MyException("exception thrown by func()");
}

int main(int argc,char* argv[]){
	cout<<"In main function"<<endl;
	try{
		func();
	}catch(MyException e){
		cout<<"Caught an exception:"<<e.getMessage()<<endl; 
	}
	cout<<"Resume the excution of main()"<<endl;
	return 0;
} 
```

```javascript
In main function
Construtor of Demo
Throw MyException in func()
Destructor of Demo
Caught an exception:excepton thrown by func()
Resume the excution of main()
```

### 2. 异常处理的语法

```c++
#include<iostream>
using namespace std;

int divide(int x,int y){
	if(y==0)
		throw x;
	return x/y;
}

int main(int argc,char*argv[]){
	try{
		cout<<"5/2="<<divide(5,2)<<endl;
		cout<<"8/0="<<divide(8,0)<<endl;
		cout<<"7/1="<<divide(7,1)<<endl;
	}catch(int e){
		cout<<e<<" is divided by zero!"<<endl;
	}
	cout<<"That is ok."<<endl;
	return 0;
} 
```

### 3. 异常接口声明

```c++
// 可以抛出且仅只能够抛出类型A,B,C,D极其子类异常
void fun() throw(A,B,C,D);
// 可以抛出任何类型的异常
void fun();
// 不抛出任何类型的异常
void fun() throw();
```

**细节**：如果一个函数抛出了它的异常接口声明所不允许抛出的异常时，unexpected 函数会被调用，该函数的默认行为是调用 terminate 函数中止程序。用户可以自己定义unexpected 函数，替换默认的函数

